with-expecter: true
packages:
  github.com/cerfical/socks2http/internal/proxy:
    interfaces:
      Proxy:
      Dialer:

outpkg: "mocks"
dir: "internal/test/mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
