with-expecter: true
packages:
  github.com/cerfical/socks2http/proxy:
    interfaces:
      Proxy:
      Dialer:

outpkg: "mocks"
dir: "test/mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
