with-expecter: true
packages:
  github.com/cerfical/socks2http/internal/proxy:
    interfaces:
      Tunneler:
      Dialer:
    config:
      dir: "internal/proxy/mocks"

outpkg: "mocks"
mockname: "{{ .InterfaceName }}"
filename: "{{ .InterfaceName | snakecase }}.go"
